version: "3"

services:
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db_name'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: root
      MYSQL_PASSWORD: password


volumes:
  mysql_data:
